driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-21
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[gunicorn::default]